### ISSUE TITLE
Replace MongoDB by a real open-source NoSQL database

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank3#12]
MongoDB runs under the server side public licence. This licence is considered as a non-free licence. Running it on servers of institutions with a commercial touch (such as GmbH) may cause unforeseen licensing issues. Even if the service is for free, research institutes are not always recognised as non-for-profit or academic. A good example of such behaviour is the change of the ElasticSearch licence to SSPL to kick out commercial providers. Thus, use another database, please. Alternatives might be Rethink DB, Couch DB and even Postgresql has NoSQL capabilities.

Thanks
Tobias

**Comment by uly55e5** [comment]
Hi Tobias,
I added PostgreSQL as an option for the database (issue #13) and I at the moment I will try to maintain both implementations for mongodb and postgres to compare performance and features. We will not use another pure NoSQL database, but it would be straightforward to implement the interface for other databases. There are interesting projects like FerretDB, which would allow to have the same query syntax as mongodb for a PostgreSQL database backend, but this is not stable at the moment. Maybe we will abandon MongoDB in the future.

**Comment by tsufz** [comment]
@uly55e5, cool! I like the idea of a more open DB interface. Thanks, Tobias
